@echo off
rem run_sim.bat - FIR Retiming project execution script for Windows

echo ===================================
echo FIR Filter Retiming Project Simulation Script (Windows)
echo ===================================

rem Check for src directory
if not exist "src" (
    echo Error: src directory not found!
    goto :eof
)

rem Create output and logs directories if they don't exist
if not exist "output" mkdir "output"
if not exist "logs" mkdir "logs"

echo Please choose a simulator:
echo 1) Icarus Verilog (Free & Open Source) - Recommended for this script
echo 2) ModelSim (Requires ModelSim installation and license)
echo 3) Quartus (For synthesis and/or ModelSim-AE)
echo 4) VCS / Xcelium (Commercial tools, not directly supported by this script)

set /p sim_choice="Enter choice (1-4): "

if "%sim_choice%"=="1" (
    echo Using Icarus Verilog...
    echo === Compiling Verilog Files ===
    iverilog -o output\fir_sim src\fir_original.v src\fir_retimed.v src\fir_retiming_tb.v > logs\compile_icarus.log 2>&1
    
    if errorlevel 1 (
        echo Compilation FAILED! Check logs\compile_icarus.log
        goto :eof
    )
    echo Compilation SUCCEEDED!
    echo === Running Simulation ===
    cd output
    vvp fir_sim > ..\logs\simulation_icarus.log 2>&1
    cd ..
    echo Simulation FINISHED!
    echo Waveform file: output\fir_retiming.vcd (if generated by testbench)
    echo Log file: logs\simulation_icarus.log
    
    set /p view_wave="Do you want to open GTKWave? (y/n; requires GTKWave in PATH): "
    if /i "%view_wave%"=="y" (
        echo Attempting to start GTKWave...
        start gtkwave output\fir_retiming.vcd
    )
    goto :post_simulation_info
)

if "%sim_choice%"=="2" (
    echo Using ModelSim...
    echo Please ensure ModelSim is installed and configured.
    echo You can run the ModelSim simulation using the Makefile:
    echo   make modelsim
    echo Or by navigating to the 'simulation' directory and running:
    echo   vsim -do modelsim.do
    echo (This script will not run it directly)
    goto :post_simulation_info
)

if "%sim_choice%"=="3" (
    echo Using Quartus...
    echo This option is for project setup or running simulations within Quartus (e.g., ModelSim-Altera Edition).
    echo You can setup the Quartus project using the Makefile:
    echo   make quartus
    echo Or by navigating to the 'scripts' directory and running:
    echo   quartus_sh -t quartus_project_setup.tcl
    echo (This script will not run it directly)
    goto :post_simulation_info
)

if "%sim_choice%"=="4" (
    echo VCS / Xcelium are commercial tools.
    echo Please use your standard workflow for these simulators.
    echo The provided Makefile might offer targets if configured, or you can adapt it.
    goto :post_simulation_info
)

echo Invalid choice!
goto :eof

:post_simulation_info
echo.
echo ===================================
echo Performance Analysis Summary (from implementation_notes.md):
echo ===================================
echo Original Design:
echo   - Critical Path: ~1 multiplier + 3 adders
echo   - Estimated Latency: ~10ns
echo   - Max Frequency: ~100MHz
echo.
echo Retimed Design:
echo   - Critical Path: max(1 multiplier, 2 adders in parallel)
echo   - Estimated Latency: ~6ns
echo   - Max Frequency: ~167MHz
echo   - Pipeline Latency: 4 clock cycles
echo   - Performance Improvement: ~67%%
echo ===================================

:eof
echo Script finished. 